apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: image-repo
  policy:
    semver:
      range: '>= 0.0.0 <99.99.99'